In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

# MATRICES

# Create a 2*2 matrix

In [16]:
matrix_one = np.array([[3,6],[5,4]])
matrix_one

array([[3, 6],
       [5, 4]])

# create a 3*3 matrix

In [17]:
matrix_two = np.array([[2,4],[4,9],[5,4]])
matrix_two

array([[2, 4],
       [4, 9],
       [5, 4]])

# Addition of Matrices

In [6]:
x = np.array([[2,6],[4,9]])
y = np.array([[8,5],[3,2]])
print(np.add(x,y))

[[10 11]
 [ 7 11]]


# Subtraction of Matrices

In [7]:
x = np.array([[2,6],[4,9]])
y = np.array([[8,5],[3,2]])
print(np.subtract(x,y))

[[-6  1]
 [ 1  7]]


# Multiplication of Matrices

In [8]:
x = np.array([[2,6],[4,9]])
y = np.array([[8,5],[3,2]])
print(np.multiply(x,y))

[[16 30]
 [12 18]]


# Division of Matrices

In [9]:
x = np.array([[2,6],[4,9]])
y = np.array([[8,5],[3,2]])
print(np.divide(x,y))

[[0.25       1.2       ]
 [1.33333333 4.5       ]]


# TRANSPOSE OF MATRICES

In [13]:
matrix_n = np.array([[4,8],[3,7],[9,6]])
matrix_n
new_matrix = np.transpose(matrix_n)
new_matrix

array([[4, 3, 9],
       [8, 7, 6]])

## Determinant of Matrices

In [14]:
x = np.array([[3,8],[2,9]])
x

array([[3, 8],
       [2, 9]])

In [15]:
det_x = np.linalg.det(x)
det_x

np.float64(11.000000000000002)